#!/usr/bin/env python


# Overall game dimensions
SCREEN_WIDTH = 960
SCREEN_HEIGHT = 720

# Welcome screen asset dimentions
START_BUTTON_WIDTH = 120
START_BUTTON_HEIGHT = 120
EXIT_BUTTON_WIDTH = 300
EXIT_BUTTON_HEIGHT = 200

#Game board asset dimensions
WIN_BUTTON_WIDTH = 100
WIN_BUTTON_HEIGHT = 100
LOSE_BUTTON_WIDTH = 100
LOSE_BUTTON_HEIGHT = 100

DEBUG_OUTPUT = False

